# Generated by Django 6.0.2 on 2026-02-21 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbercar',
            name='tags',
            field=models.ManyToManyField(blank=True, to='relation_db.tag'),
        ),
    ]
