# Generated by Django 6.0.2 on 2026-02-21 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relation_db', '0002_alter_numbercar_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numbercar',
            name='tags',
            field=models.ManyToManyField(null=True, to='relation_db.tag'),
        ),
    ]
